// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// endpoints

#include "microcoap/coap.h"


static const coap_endpoint_path_t TUTCI__coapled__paths_get_well_known_core = {2, {".well-known", "core"}};

int TUTCI__coapled__handle_get_well_known_core(coap_rw_buffer_t *scratch,
const coap_packet_t *inpkt, coap_packet_t *outpkt,
uint8_t id_hi, uint8_t id_lo);



// enumerate all single resources as endpoint_path types

static const coap_endpoint_path_t TUTCI__coapled__paths__digit = {1, {"digit"}};

// define handler functions

int TUTCI__coapled__handle_get___digit(coap_rw_buffer_t *scratch,
    const coap_packet_t *inpkt, coap_packet_t *outpkt,
    uint8_t id_hi, uint8_t id_lo);

int TUTCI__coapled__handle_post___digit(coap_rw_buffer_t *scratch,
    const coap_packet_t *inpkt, coap_packet_t *outpkt,
    uint8_t id_hi, uint8_t id_lo);


// define array with all endpoints
extern const coap_endpoint_t endpoints[] =
{

    {COAP_METHOD_GET, TUTCI__coapled__handle_get_well_known_core, &TUTCI__coapled__paths_get_well_known_core, "ct=40"},

    {COAP_METHOD_GET, TUTCI__coapled__handle_get___digit, &TUTCI__coapled__paths__digit, "ct=0"},	/* Return device configuration */
    {COAP_METHOD_POST, TUTCI__coapled__handle_post___digit, &TUTCI__coapled__paths__digit, "ct=0"},	/* Update device configuration */
    {(coap_method_t)0, NULL, NULL, NULL}
};
