
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// application-part header



    #include "Arduino.h"

#include "microcoap/coap.h"

// include data structure headers
#include "counter.h"

// struct TUTCI__counter
#include "counter.h"



//
// CoAP Application level handlers
//

// -- GET  /digit

struct TUTCI__coapled__get___digit_req {
    struct {

    } data;
};

struct TUTCI__coapled__get___digit_resp {
    coap_responsecode_t  response_code;
    struct {


        // data struct for response code 205
        struct TUTCI__counter  counter_205;

    } data;
};

// -- Application level handler for GET to /digit
bool TUTCI__coapled__get___digit(
    struct TUTCI__coapled__get___digit_req *req,
    struct TUTCI__coapled__get___digit_resp *resp);


// -- POST  /digit

struct TUTCI__coapled__post___digit_req {
    struct {

        struct TUTCI__counter  counter;

    } data;
};

struct TUTCI__coapled__post___digit_resp {
    coap_responsecode_t  response_code;
    struct {

    } data;
};

// -- Application level handler for POST to /digit
bool TUTCI__coapled__post___digit(
    struct TUTCI__coapled__post___digit_req *req,
    struct TUTCI__coapled__post___digit_resp *resp);
