
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.


#include "Arduino.h"

#include "counter.h"
#include "mpack/mpack.h"
#include "mpack/mpack-platform.h"

void TUTCI__counter_clean(struct TUTCI__counter *self) {

	self->command = false;
}

void TUTCI__counter_parse_next(struct TUTCI__counter *self, mpack_reader_t *reader) {

	char	buf_key[8];
	mpack_expect_utf8_cstr(reader, buf_key, sizeof(buf_key));


	if (mpack_memcmp("command",(const char*)buf_key,7) == 0) {
		self->command = mpack_expect_bool(reader);
	}


}

int TUTCI__counter_parse(struct TUTCI__counter *self, const uint8_t *input_buf, size_t sz_input_buf) {
		mpack_reader_t reader;
    mpack_error_t error;

    mpack_reader_init_data(&reader,(const char *)input_buf, sz_input_buf);
    self->TUTCI__counter_parse_mpack(self, &reader);

    error = mpack_reader_destroy(&reader);
    if ( error != mpack_ok) {
        return 1;
    } else {
        return 0;
    }

}

void TUTCI__counter_parse_mpack(struct TUTCI__counter *self, mpack_reader_t *reader) {

    int count = mpack_expect_map_range(reader, 1, 1);
    for (int i = 0; i < count; i++) {
        TUTCI__counter_parse_next(self, reader);
    }

    mpack_done_map(reader);
}

size_t TUTCI__counter_serialize(const struct TUTCI__counter *self, uint8_t *output_buf, size_t sz_output_buf) {
		struct mpack_writer_t writer;
    mpack_writer_init(&writer,(char*)output_buf,sz_output_buf);

		self->TUTCI__counter_serialize_mpack(self, &writer);

    mpack_writer_flush_message(&writer);
    size_t used = mpack_writer_buffer_used(&writer);

    // if all is ok, return length of used bytes. Otherwise 0
    if (mpack_writer_destroy(&writer) == mpack_ok) {
        return used;
    } else {
        return (size_t)0;
    }
}

void TUTCI__counter_serialize_mpack(const struct TUTCI__counter *self, mpack_writer_t *writer) {
    mpack_start_map(writer, 1);

	mpack_write_cstr(writer, "command"); mpack_write_bool(writer, self->command);

    mpack_finish_map(writer);
}

void TUTCI__counter_init(struct TUTCI__counter *self) {
    self->TUTCI__counter_clean = &TUTCI__counter_clean;
    self->TUTCI__counter_parse = &TUTCI__counter_parse;
    self->TUTCI__counter_parse_mpack = &TUTCI__counter_parse_mpack;
    self->TUTCI__counter_serialize = &TUTCI__counter_serialize;
    self->TUTCI__counter_serialize_mpack = &TUTCI__counter_serialize_mpack;
    self->TUTCI__counter_clean(self);
}

//
